modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Cursed-Loot/issues"
license="MIT"

[[mods]]
modId="cursedloot"
version="${file.jarVersion}"
displayName="Cursed Loot"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cursed-loot"
authors="Mrbysco, ShyNieke"
description='''
Adds cursed loot to the game.
'''
credits="Credits to the game Moonlighter for sparking the idea"

[[dependencies.cursedloot]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.cursedloot]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"