modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Mrbysco/Cursed-Loot/issues"
license="MIT"

[[mods]]
modId="cursedloot"
version="${file.jarVersion}"
displayName="Cursed Loot"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cursed-loot"
authors="Mrbysco, ShyNieke"
description='''
Adds cursed loot to the game.
'''
credits="Credits to the game Moonlighter for sparking the idea"

[[dependencies.cursedloot]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"